In [1]:
from Experiments import *
from utils.visualization import *
import torch
import torch.optim as optim

In [2]:
torch.cuda.manual_seed(0)
torch.manual_seed(0)
device = torch.device('cuda')

In [3]:
hparams = Hyperparameters()
hparams.set_model_size([2, 48, 48, 48, 1])
hparams.set_epochs(50000) # 50000
hparams.set_device(device)

In [4]:
hparams.set_lr(1e-4)
additional_str = '_RMSprop_train_1_Inverse'
expt = InverseExperiement(InverseHeatEquation(), hparams, optim.RMSprop, additional_str)
expt.train_and_test_on_all_activations()

Computing and Saving Analytical Solution
Training for activation fn: ReLU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


  0%|          | 0/50000 [00:00<?, ?it/s]/home/airl-gpu5-mini/anaconda3/envs/PhysicsModels/lib/python3.9/site-packages/torch/autograd/graph.py:744: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
100%|██████████| 50000/50000 [14:05<00:00, 59.14it/s]


final
Parameter containing:
tensor([1.4623], requires_grad=True)
Training for activation fn: Sigmoid
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [15:55<00:00, 52.32it/s]


final
Parameter containing:
tensor([0.2521], requires_grad=True)
Training for activation fn: Softplus
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [16:49<00:00, 49.51it/s]


final
Parameter containing:
tensor([0.3351], requires_grad=True)
Training for activation fn: GELU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [16:50<00:00, 49.46it/s]


final
Parameter containing:
tensor([0.3998], requires_grad=True)
Training for activation fn: tanh(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [15:37<00:00, 53.31it/s]


final
Parameter containing:
tensor([0.4003], requires_grad=True)
Training for activation fn: sin(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [16:06<00:00, 51.73it/s]


final
Parameter containing:
tensor([0.3960], requires_grad=True)
Training for activation fn: sech(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [21:19<00:00, 39.08it/s]


final
Parameter containing:
tensor([0.3930], requires_grad=True)
Training for activation fn: (ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [25:11<00:00, 33.07it/s]


final
Parameter containing:
tensor([0.3974], requires_grad=True)
Training for activation fn: sin(ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [25:34<00:00, 32.58it/s]


final
Parameter containing:
tensor([0.3993], requires_grad=True)
Training for activation fn: STan-LAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [22:04<00:00, 37.76it/s]


final
Parameter containing:
tensor([0.4000], requires_grad=True)
Training for activation fn: STan-NLAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [22:27<00:00, 37.09it/s]


final
Parameter containing:
tensor([0.3996], requires_grad=True)
Training for activation fn: REAct-LAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [28:02<00:00, 29.72it/s]


final
Parameter containing:
tensor([0.3997], requires_grad=True)
Training for activation fn: REAct-NLAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [29:58<00:00, 27.80it/s]


final
Parameter containing:
tensor([0.3991], requires_grad=True)
Training for activation fn: ABU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 50000/50000 [30:06<00:00, 27.68it/s]


final
Parameter containing:
tensor([1.1132], requires_grad=True)
|                         |   l2_relative_error |   mean_squared_error |   mean_absolute_error |   explained_variance_score |   est. param value |   pc. error in param value |
|:------------------------|--------------------:|---------------------:|----------------------:|---------------------------:|-------------------:|---------------------------:|
| ReLU                    |          1.09158    |          0.0755742   |            0.228156   |                   0.148067 |            1.11316 |                    178.291 |
| Sigmoid                 |          0.268789   |          0.00458236  |            0.055454   |                   0.934659 |            1.11316 |                    178.291 |
| Softplus                |          0.14336    |          0.00130352  |            0.0308565  |                   0.98991  |            1.11316 |                    178.291 |
| GELU                    |          0.0134695  |      

In [5]:
hparams.set_lr(1e-3)
additional_str = '_Adam_train_1_Inverse'
expt = InverseExperiement(InverseHeatEquation(), hparams, optim.Adam, additional_str)
expt.train_and_test_on_all_activations()

Computing and Saving Analytical Solution
Training for activation fn: ReLU
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [14:51<00:00, 56.10it/s]


final
Parameter containing:
tensor([1.7081], requires_grad=True)
Training for activation fn: Sigmoid
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [16:27<00:00, 50.64it/s] 


final
Parameter containing:
tensor([0.3997], requires_grad=True)
Training for activation fn: Softplus
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [17:41<00:00, 47.08it/s]


final
Parameter containing:
tensor([0.3981], requires_grad=True)
Training for activation fn: GELU
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [17:42<00:00, 47.08it/s] 


final
Parameter containing:
tensor([0.3998], requires_grad=True)
Training for activation fn: tanh(x)
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [15:55<00:00, 52.32it/s] 


final
Parameter containing:
tensor([0.3999], requires_grad=True)
Training for activation fn: sin(x)
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [16:16<00:00, 51.19it/s]


final
Parameter containing:
tensor([0.3993], requires_grad=True)
Training for activation fn: sech(x)
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [25:09<00:00, 33.13it/s]


final
Parameter containing:
tensor([0.3999], requires_grad=True)
Training for activation fn: (ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [25:43<00:00, 32.39it/s]


final
Parameter containing:
tensor([0.3994], requires_grad=True)
Training for activation fn: sin(ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [26:07<00:00, 31.89it/s]


final
Parameter containing:
tensor([0.3995], requires_grad=True)
Training for activation fn: STan-LAAF
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [22:51<00:00, 36.45it/s]


final
Parameter containing:
tensor([0.4006], requires_grad=True)
Training for activation fn: STan-NLAAF
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [23:21<00:00, 35.68it/s]


final
Parameter containing:
tensor([0.4000], requires_grad=True)
Training for activation fn: REAct-LAAF
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [29:00<00:00, 28.74it/s]


final
Parameter containing:
tensor([0.3999], requires_grad=True)
Training for activation fn: REAct-NLAAF
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [32:22<00:00, 25.74it/s]


final
Parameter containing:
tensor([nan], requires_grad=True)
Training for activation fn: ABU
init
Parameter containing:
tensor([1.7081], requires_grad=True)


100%|██████████| 50000/50000 [31:43<00:00, 26.26it/s]


final
Parameter containing:
tensor([1.5335], requires_grad=True)
|                         |   l2_relative_error |   mean_squared_error |   mean_absolute_error |   explained_variance_score |   est. param value |   pc. error in param value |
|:------------------------|--------------------:|---------------------:|----------------------:|---------------------------:|-------------------:|---------------------------:|
| ReLU                    |          1.09017    |          0.0753789   |           0.226867    |                   0.133994 |            1.53349 |                    283.373 |
| Sigmoid                 |          0.0122019  |          9.44326e-06 |           0.00299196  |                   0.999987 |            1.53349 |                    283.373 |
| Softplus                |          0.00421416 |          1.12638e-06 |           0.000871623 |                   0.999984 |            1.53349 |                    283.373 |
| GELU                    |          0.00164792 |      