In [1]:
from Experiments import *
from utils.visualization import *
import torch
import torch.optim as optim

In [2]:
torch.cuda.manual_seed(0)
torch.manual_seed(0)
device = torch.device('cuda:1')

In [3]:
hparams = Hyperparameters()
hparams.set_model_size([2, 60, 60, 60, 1])
hparams.set_epochs(75000) # 75000
hparams.set_device(device)

In [4]:
hparams.set_lr(1e-4)
additional_str = '_RMSprop_train_1_Inverse'
expt = InverseExperiement(InverseWaveEquation(), hparams, optim.RMSprop, additional_str)
expt.train_and_test_on_all_activations()

Computing and Saving Analytical Solution
Training for activation fn: ReLU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [25:32<00:00, 48.93it/s]


final
Parameter containing:
tensor([1.4623], requires_grad=True)
Training for activation fn: Sigmoid
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [29:55<00:00, 41.78it/s] 


final
Parameter containing:
tensor([1.9871], requires_grad=True)
Training for activation fn: Softplus
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [32:03<00:00, 39.00it/s]


final
Parameter containing:
tensor([1.9814], requires_grad=True)
Training for activation fn: GELU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [31:26<00:00, 39.76it/s] 


final
Parameter containing:
tensor([1.9962], requires_grad=True)
Training for activation fn: tanh(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [30:22<00:00, 41.15it/s]


final
Parameter containing:
tensor([1.9962], requires_grad=True)
Training for activation fn: sin(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [30:12<00:00, 41.39it/s]


final
Parameter containing:
tensor([1.9951], requires_grad=True)
Training for activation fn: sech(x)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [42:22<00:00, 29.50it/s]


final
Parameter containing:
tensor([1.9967], requires_grad=True)
Training for activation fn: (ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [40:18<00:00, 31.02it/s]


final
Parameter containing:
tensor([1.9865], requires_grad=True)
Training for activation fn: sin(ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [44:45<00:00, 27.93it/s]


final
Parameter containing:
tensor([1.9912], requires_grad=True)
Training for activation fn: STan-LAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [38:13<00:00, 32.70it/s]


final
Parameter containing:
tensor([1.9942], requires_grad=True)
Training for activation fn: STan-NLAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [37:12<00:00, 33.59it/s]


final
Parameter containing:
tensor([1.9916], requires_grad=True)
Training for activation fn: REAct-LAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [50:14<00:00, 24.88it/s]


final
Parameter containing:
tensor([1.9968], requires_grad=True)
Training for activation fn: REAct-NLAAF
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [53:38<00:00, 23.30it/s]


final
Parameter containing:
tensor([1.9881], requires_grad=True)
Training for activation fn: ABU
init
Parameter containing:
tensor([1.4623], requires_grad=True)


100%|██████████| 75000/75000 [51:25<00:00, 24.31it/s]


final
Parameter containing:
tensor([1.7735], requires_grad=True)
|                         |   l2_relative_error |   mean_squared_error |   mean_absolute_error |   explained_variance_score |   est. param value |   pc. error in param value |
|:------------------------|--------------------:|---------------------:|----------------------:|---------------------------:|-------------------:|---------------------------:|
| ReLU                    |          0.0300901  |          0.000226353 |            0.0131022  |                   0.999708 |            1.77346 |                    11.3269 |
| Sigmoid                 |          0.0348436  |          0.000303519 |            0.0150911  |                   0.99965  |            1.77346 |                    11.3269 |
| Softplus                |          0.0595556  |          0.000886717 |            0.0256494  |                   0.999032 |            1.77346 |                    11.3269 |
| GELU                    |          0.00515907 |      

In [5]:
hparams.set_lr(1e-3)
additional_str = '_Adam_train_1_Inverse'
expt = InverseExperiement(InverseWaveEquation(), hparams, optim.Adam, additional_str)
expt.train_and_test_on_all_activations()

Computing and Saving Analytical Solution
Training for activation fn: ReLU
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [26:48<00:00, 46.63it/s]


final
Parameter containing:
tensor([1.4968], requires_grad=True)
Training for activation fn: Sigmoid
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [31:40<00:00, 39.47it/s]


final
Parameter containing:
tensor([1.9995], requires_grad=True)
Training for activation fn: Softplus
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [33:27<00:00, 37.36it/s]


final
Parameter containing:
tensor([1.9996], requires_grad=True)
Training for activation fn: GELU
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [33:49<00:00, 36.95it/s]


final
Parameter containing:
tensor([1.9996], requires_grad=True)
Training for activation fn: tanh(x)
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [31:09<00:00, 40.12it/s]


final
Parameter containing:
tensor([1.9999], requires_grad=True)
Training for activation fn: sin(x)
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [31:57<00:00, 39.12it/s]


final
Parameter containing:
tensor([1.9992], requires_grad=True)
Training for activation fn: sech(x)
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [43:50<00:00, 28.52it/s]


final
Parameter containing:
tensor([2.0001], requires_grad=True)
Training for activation fn: (ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [45:16<00:00, 27.61it/s]


final
Parameter containing:
tensor([2.0000], requires_grad=True)
Training for activation fn: sin(ax + b)tanh(cx + d)
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [47:53<00:00, 26.10it/s]


final
Parameter containing:
tensor([1.9997], requires_grad=True)
Training for activation fn: STan-LAAF
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [39:15<00:00, 31.84it/s]


final
Parameter containing:
tensor([1.9995], requires_grad=True)
Training for activation fn: STan-NLAAF
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [40:36<00:00, 30.79it/s]


final
Parameter containing:
tensor([1.9995], requires_grad=True)
Training for activation fn: REAct-LAAF
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [52:12<00:00, 23.94it/s]


final
Parameter containing:
tensor([1.9993], requires_grad=True)
Training for activation fn: REAct-NLAAF
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [55:31<00:00, 22.51it/s] 


final
Parameter containing:
tensor([1.9990], requires_grad=True)
Training for activation fn: ABU
init
Parameter containing:
tensor([1.4968], requires_grad=True)


100%|██████████| 75000/75000 [55:25<00:00, 22.55it/s] 


final
Parameter containing:
tensor([1.9933], requires_grad=True)
|                         |   l2_relative_error |   mean_squared_error |   mean_absolute_error |   explained_variance_score |   est. param value |   pc. error in param value |
|:------------------------|--------------------:|---------------------:|----------------------:|---------------------------:|-------------------:|---------------------------:|
| ReLU                    |          1.01427    |          0.257187    |           0.385012    |                   0.23596  |            1.99325 |                   0.337374 |
| Sigmoid                 |          0.00946845 |          2.24129e-05 |           0.00463844  |                   0.999996 |            1.99325 |                   0.337374 |
| Softplus                |          0.00436213 |          4.75704e-06 |           0.0017725   |                   0.999983 |            1.99325 |                   0.337374 |
| GELU                    |          0.00115891 |      